# Data Structure {#data-structure}

## Collected SGBA-5 Responses

After collecting responses from the SGBA-5 you will have a dataset that looks something like this:

``` {r 01-data, echo=FALSE}
# load library
library(tidyverse)

# example of collected data
SGBA5_response <- tibble(
  pt_id = 1:5,
  sex = c("Female", "Male", "Female", "Female", "Male"),
  gen_id = sample(0:100, 5, replace=TRUE),
  gen_exp = sample(0:100, 5, replace=TRUE),
  gen_role = sample(0:100, 5, replace=TRUE),
  gen_rel = sample(0:100, 5, replace=TRUE),
)

knitr::kable(SGBA5_response, booktabs = TRUE, caption = "Example Data Structure") %>%
  kableExtra::add_footnote("The values in this table are placeholders for the example, not real data", notation = "none")
```

Where:  

`pt_id` is the participant identifier.  

`sex` is the SGBA-5 categorical Biological Sex item.  

  - response options of "male", "female", and "intersex".  

`gen_id` is the SGBA-5 Gender Identity gendered aspect of health item.  

  - Responses are recorded as ordinal values between 0 to 100 on a feminine to masculine scale (measured in mm if completed on paper).  

`gen_exp` is the SGBA-5 Gender Expression gendered aspect of health item.  

  - Responses are recorded as ordinal values between 0 to 100 on a feminine to masculine scale (measured in mm if completed on paper).  

`gen_role` is the SGBA-5 Gender Role gendered aspect of health item.  

  - Responses are recorded as ordinal values between 0 to 100 on a feminine to masculine scale (measured in mm if completed on paper).  

`gen_rel` is the SGBA-5 Gender Relations gendered aspect of health item.  

  - Responses are recorded as ordinal values between 0 to 100 on a feminine to masculine scale (measured in mm if completed on paper).


## Simulated Data

This example analysis uses simulated data, if you wish to replicate the simulate data the code to do so is included in [Appendix A]() or can be downloaded from this example's [github page](https://github.com/putman-a/SGBA-5_example_analysis/%s).
